name: 📚 Content Suggestion
description: 🎓 Have an idea for new educational content? Share it with us!
title: "📚 [CONTENT] "
labels: ["📚 content", "💡 suggestion", "🎓 education", "🔍 needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 Thanks for helping us grow our educational content!
        
        📚 **Educational content ideas are gold!** Your suggestions help millions of learners.
        🎯 **The more specific, the better!** Details help us create exactly what learners need.
        
  - type: dropdown
    id: content-type
    attributes:
      label: 📖 What type of content are you suggesting?
      description: Help us categorize your awesome idea
      options:
        - 📐 Mathematics - Algebra, geometry, calculus, etc.
        - 🔬 Science - Physics, chemistry, biology, etc.
        - 📊 Statistics & Data - Statistics, probability, data analysis
        - 💻 Computer Science - Programming, algorithms, data structures
        - 🌍 Social Studies - History, geography, politics, economics  
        - 🗣️ Languages - English, Indonesian, literature
        - 🎨 Arts & Creativity - Visual arts, music, design
        - 🏃 Physical Education - Sports, health, fitness
        - 🤔 Critical Thinking - Logic, philosophy, problem-solving
        - 📋 Study Skills - Learning techniques, organization, time management
        - 🌟 Other - Something unique and different!
      default: 10
    validations:
      required: true
      
  - type: dropdown
    id: education-level
    attributes:
      label: 🎓 Which education level is this for?
      description: Target audience for your content suggestion
      options:
        - 👶 Elementary School (Grades 1-6)
        - 🧑 Middle School (Grades 7-9)
        - 👨‍🎓 High School (Grades 10-12)
        - 🎓 University/College Level
        - 👨‍🏫 Teachers & Educators
        - 👥 General/All Levels
        - 🤷 Not sure - Help me decide!
      default: 5
    validations:
      required: true
      
  - type: textarea
    id: content-description
    attributes:
      label: 📝 What content would you like to see?
      description: Describe your content idea in detail
      placeholder: |
        Example: "I'd love to see an interactive lesson about photosynthesis for middle school students. It could include:
        - A 3D plant model showing how sunlight, water, and CO2 work together
        - Step-by-step animations of the chemical reactions
        - Interactive quizzes to test understanding
        - Real-world examples of how different plants photosynthesize"
    validations:
      required: true
      
  - type: textarea
    id: learning-objectives
    attributes:
      label: 🎯 What should students learn from this?
      description: What key concepts or skills should this content teach?
      placeholder: |
        📚 Learning objectives (e.g.):
        - Understand the basic process of photosynthesis
        - Identify the role of chloroplasts in plants
        - Explain how plants convert light energy to chemical energy
        - Apply knowledge to real-world plant biology
    validations:
      required: false
      
  - type: textarea
    id: why-important
    attributes:
      label: 🌟 Why is this content important?
      description: Help us understand the impact and value
      placeholder: |
        💡 Why does this matter? For example:
        - Fills a gap in current curriculum
        - Addresses common student struggles
        - Prepares students for advanced topics
        - Connects to real-world applications
        - Makes learning more engaging and fun
    validations:
      required: true
      
  - type: dropdown
    id: content-format
    attributes:
      label: 🎥 What format would work best?
      description: How do you envision this content being presented?
      options:
        - 📖 Written Article/Lesson - Traditional text-based content
        - 🎥 Video Lesson - Animated or recorded video content
        - 🎮 Interactive Exercise - Hands-on practice and games
        - 📊 Visual Infographic - Charts, diagrams, and visuals
        - 🧪 Virtual Lab/Simulation - Interactive experiments
        - 📱 Mobile-Friendly Activity - Optimized for mobile learning
        - 🎭 Storytelling/Narrative - Learning through stories
        - 🧩 Multiple Formats - Combination of different approaches
      default: 7
    validations:
      required: true
      
  - type: textarea
    id: examples-references
    attributes:
      label: 🔗 Examples or References
      description: Share links, books, or examples that inspired your idea
      placeholder: |
        📚 References that might help:
        - Links to similar content you've seen
        - Textbooks or educational resources
        - YouTube videos or other educational content
        - Academic papers or research
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: ⚡ How important is this content to you?
      description: Help us understand the urgency and impact
      options:
        - 🔥 Critical - Essential for current learning needs
        - ⭐ High - Would significantly improve learning experience
        - 👍 Medium - Nice addition to the platform
        - 💡 Low - Interesting idea for future consideration
      default: 2
    validations:
      required: true
      
  - type: textarea
    id: target-audience
    attributes:
      label: 👥 Who would benefit most from this?
      description: Describe the ideal learner for this content
      placeholder: |
        🎯 Target audience details:
        - Age range and grade level
        - Prior knowledge requirements
        - Learning style preferences
        - Specific challenges they face
        - How they would use this content
    validations:
      required: false
      
  - type: textarea
    id: additional-ideas
    attributes:
      label: 💬 Any other thoughts?
      description: Share any additional ideas, suggestions, or context
      placeholder: "✨ Any other creative ideas, related topics, or ways to make this content even more amazing?"
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Content Creator's Check
      description: Let's make sure we're aligned on creating great educational content
      options:
        - label: 🔍 I've checked if similar content already exists on the platform
          required: true
        - label: 📚 This content aligns with educational standards and learning objectives
          required: true
        - label: 🌍 I've considered accessibility and inclusivity in my suggestion
          required: true
        - label: 🤝 I understand that content creation takes time and community input
          required: true 