name: ⚡ Performance & Accessibility
description: 🌍 Help us make nakafa faster and accessible to everyone!
title: "⚡ [PERF/A11Y] "
labels: ["⚡ performance", "♿ accessibility", "🎨 UX", "🔍 needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Thanks for helping make nakafa better for everyone!
        
        ⚡ **Performance matters!** Fast loading = better learning experience.
        ♿ **Accessibility is essential!** Everyone deserves equal access to education.
        🎨 **Great UX = Happy learners!** Small improvements make big differences.
        
  - type: dropdown
    id: issue-type
    attributes:
      label: 🎯 What type of issue is this?
      description: Help us categorize your report
      options:
        - ⚡ Performance - Slow loading, lag, or responsiveness issues
        - ♿ Accessibility - Screen reader, keyboard navigation, or disability barriers
        - 📱 Mobile Experience - Mobile-specific usability issues
        - 🎨 User Interface - Visual design or layout problems
        - 🔤 Typography - Text readability or font issues
        - 🎨 Color/Contrast - Color accessibility or visual clarity
        - ⌨️ Keyboard Navigation - Tab order or keyboard-only usage
        - 🔊 Audio/Visual - Multimedia accessibility issues
        - 🌐 Cross-browser - Browser compatibility problems
        - 🌍 Internationalization - Language or localization issues
        - 🤷 Not Sure - Multiple issues or unsure how to categorize
      default: 10
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: 🔍 What's the issue?
      description: Describe the performance or accessibility problem you've encountered
      placeholder: |
        Example: "The mathematics visualization page takes 15+ seconds to load on mobile devices. The 3D models seem to be causing the issue. When they finally load, the page becomes unresponsive when trying to interact with the models..."
    validations:
      required: true
      
  - type: dropdown
    id: severity-impact
    attributes:
      label: 📊 How severe is the impact?
      description: Help us understand how this affects users
      options:
        - 🚨 Critical - Completely blocks access or usage
        - ⚠️ High - Significantly impacts user experience
        - 📋 Medium - Noticeable but manageable impact
        - 💡 Low - Minor improvement opportunity
      default: 2
    validations:
      required: true
      
  - type: textarea
    id: affected-users
    attributes:
      label: 👥 Who is affected?
      description: Help us understand which users experience this issue
      placeholder: |
        🎯 Affected user groups (check all that apply):
        - 📱 Mobile users
        - ♿ Users with disabilities (specify: vision, hearing, motor, cognitive)
        - 👴 Older users or those less tech-savvy
        - 🌐 Users on slow internet connections
        - 🌍 International users (specific regions/languages)
        - 📚 Specific education levels (elementary, high school, etc.)
        - 🔧 Users with assistive technologies (screen readers, etc.)
    validations:
      required: true
      
  - type: textarea
    id: device-environment
    attributes:
      label: 📱 Device & Environment Details
      description: Technical details about where you encountered this issue
      placeholder: |
        📊 Technical environment:
        📱 Device: iPhone 13, Samsung Galaxy, MacBook Pro, etc.
        🌐 Browser: Chrome 120, Safari 17, Firefox 115, etc.
        💻 OS: iOS 17, Android 14, macOS 14, Windows 11, etc.
        🔗 Connection: WiFi, 4G, 5G, slow connection, etc.
        📍 Specific page: https://nakafa.com/subject/mathematics/...
        ♿ Assistive tech: Screen reader, voice control, etc.
      value: |
        📱 Device: 
        🌐 Browser: 
        💻 OS: 
        🔗 Connection: 
        📍 Page: 
        ♿ Assistive tech: 
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 How to reproduce this issue?
      description: Step-by-step instructions to experience the problem
      placeholder: |
        📝 Steps to reproduce:
        1. 🌐 Go to [specific page]
        2. 👆 Click/tap on [specific element]
        3. ⌨️ Use keyboard to navigate or [specific action]
        4. ⏱️ Notice the delay/issue after [time/action]
        5. 📱 Try on mobile vs desktop
    validations:
      required: true
      
  - type: textarea
    id: expected-vs-actual
    attributes:
      label: ✅ Expected vs. Actual Behavior
      description: What should happen vs. what actually happens?
      placeholder: |
        ✅ Expected: Page loads within 2-3 seconds, all interactive elements work smoothly
        ❌ Actual: Page takes 15+ seconds to load, models are unresponsive, causes browser lag
        
        ✅ Expected: Screen reader announces all content clearly
        ❌ Actual: Math equations are read as gibberish, navigation is confusing
    validations:
      required: true
      
  - type: textarea
    id: performance-metrics
    attributes:
      label: 📈 Performance Metrics (if available)
      description: Any performance data, test results, or measurements you have
      placeholder: |
        📊 Performance data (if you have it):
        - ⏱️ Load time: 15 seconds
        - 📊 Lighthouse score: Performance 30/100
        - 🔧 DevTools info: Large bundle size, many requests
        - ♿ Accessibility score: 65/100
        - 📱 Mobile PageSpeed: Poor
        - 🖥️ Memory usage: High
    validations:
      required: false
      
  - type: textarea
    id: screenshots-evidence
    attributes:
      label: 📸 Screenshots or Evidence
      description: Visual proof helps us understand and fix the issue faster
      placeholder: |
        🖼️ Visual evidence:
        - Screenshots of the issue
        - Screen recordings showing the problem
        - DevTools screenshots (Network, Performance tabs)
        - Accessibility testing results
        - Before/after comparisons
    validations:
      required: false
      
  - type: textarea
    id: suggested-solutions
    attributes:
      label: 💡 Suggested Solutions
      description: Any ideas for how this could be improved?
      placeholder: |
        🔧 Possible solutions (if you have ideas):
        - Optimize images/3D models for mobile
        - Add loading states and skeleton UI
        - Implement lazy loading for heavy content
        - Add alt text for images and proper ARIA labels
        - Improve keyboard navigation order
        - Add reduced motion options
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: 💬 Additional Context
      description: Any other information that might help us address this issue?
      placeholder: "✨ Related issues, user feedback, testing tools used, or any other helpful context..."
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Performance & Accessibility Check
      description: Helping us ensure comprehensive improvements
      options:
        - label: 🔍 I've checked if this issue has been reported before
          required: true
        - label: 📊 I've tested this on multiple devices/browsers when possible
          required: true
        - label: ♿ I understand this affects real users' ability to access education
          required: true
        - label: 🤝 I'm willing to help test fixes if needed
          required: false 