name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Use oven-sh/setup-bun action to install Bun
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest # Or specify a specific bun version

    # Setup Node.js (Bun needs Node.js runtime)
    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        # Cache dependencies based on bun.lockb
        cache: 'bun'

    - name: Install dependencies
      run: bun install --frozen-lockfile # Use bun install with frozen lockfile for CI

    - name: Run linters # Assumes 'lint' script exists in package.json
      run: bun run lint --if-present

    - name: Run tests # Assumes 'test' script exists in package.json
      run: bun run test --if-present

    - name: Build project # Assumes 'build' script exists in package.json
      run: bun run build --if-present 